### ISSUE TITLE
[FRONTEND] Add link to Palembang Digital YouTube Channel

### ISSUE THREAD

**Issue by ariefrahmansyah** [palembang-digital/web-frontend#15]
It will be great to have a link to our YouTube channel. We can put it on footer section as well alongside other social links.

Here's the link: https://www.youtube.com/channel/UCc2Wluk3SISRSNzNlxaQ1Fw

**Comment by taufik230301** [comment]
Sran, taro dibagian social media kk, di footer

**Comment by salahudinalyb** [comment]
iyo benar kak, setuju sm taufik
