### ISSUE TITLE
[DESIGN] Media coverage at Homepage

### ISSUE THREAD

**Issue by tokanggit** [palembang-digital/web-frontend#22]
Please add media coverage (Diliput Oleh) section before sponsor

**Comment by rizqiadisurya** [comment]
![Screen Shot 2020-06-17 at 16 57 21](https://user-images.githubusercontent.com/10339802/84884263-b3cab280-b0bb-11ea-8870-bfca4b197eef.png)
kak untuk yang media coverage udah aku buat kak
