### ISSUE TITLE
[DESIGN] Patal homepage mobile view

### ISSUE THREAD

**Issue by tokanggit** [palembang-digital/web-frontend#25]
Design patal homepage for mobile view

it should be very simple,

every event and sponsor section only shows once at a time, and user is expected to swipe left or right to see next or previous event.

Reference: https://seopressor.com/blog/beautiful-examples-mobile-friendly-websites/

**Comment by salahudinalyb** [comment]
berarti kalo team page ado task dewek, yg task ini homepage done kak, eventnyo kubuat slide kiri atau kanan be biar enak pengunjung enak ngeliat event2 sdh dsikusi jg sm frontend (udin)

**Comment by tokanggit** [comment]
boleh minta link figmanyo buat di review?

**Comment by salahudinalyb** [comment]
ini kak

https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=0%3A1

**Comment by tokanggit** [comment]
yang sponsor idak dibikin slide jg bro? kecik nian agek di mobile

**Comment by salahudinalyb** [comment]
done kakk

https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=0%3A1

**Comment by tokanggit** [comment]
LGTM
