### ISSUE TITLE
[DESIGN] Patal Team Page mobile view

### ISSUE THREAD

**Issue by tokanggit** [palembang-digital/web-frontend#26]
Only show name, position and profile url without avatar image

**Comment by rizqiadisurya** [comment]
![Screen Shot 2020-06-24 at 19 17 03](https://user-images.githubusercontent.com/10339802/85554883-8e0b5380-b64f-11ea-98b6-9640f18cba4e.png)

untuk team aku pake-in card kak

**Comment by tokanggit** [comment]
@rizqiadisurya oke boleh, tolong share link figmanyo kesini e
