### ISSUE TITLE
Configure Favicon and Title

### ISSUE THREAD

**Issue by ariefrahmansyah** [palembang-digital/web-frontend#4]
1. We are still using the default Gatsby favicon. We need to change it to Palembang Digital's icon.
2. The title should be `Palembang Digital` instead of displaying the URL.

![image](https://user-images.githubusercontent.com/8122852/83981903-bc511980-a954-11ea-887e-d36115fa7eb1.png)

**Comment by Misbahudin04** [comment]
aku pick ini yah kak, caranya mungkin aku ganti di index.html nya boleh kak?

**Comment by ariefrahmansyah** [comment]
> aku pick ini yah kak, caranya mungkin aku ganti di index.html nya boleh kak?

index.html kan generated file. i don't think you can just change index.html

i believe gatsby provide better way to configure this. maybe you can check gatsby config or plugin?

**Comment by Misbahudin04** [comment]
gatsby-plugin-react-head ya kak

**Comment by Misbahudin04** [comment]
![head](https://user-images.githubusercontent.com/65540529/83991669-af91ed00-a977-11ea-8c23-65e4ee3b4d3b.JPG) ini pakek gatsby-react-head-kak

**Comment by ariefrahmansyah** [comment]
Cool. It looks legit.

Okay, I'll assign this issue to you.

**Comment by tokanggit** [comment]
https://trello-attachments.s3.amazonaws.com/5ec26716ac44b18e44b0c713/5ec26ed1ca8c211db94ada74/c08d74fbd8ec5de958005d637674d033/favicon.ico

link for the favicon
