### ISSUE TITLE
[DESIGN] Add Patal basecamp address at footer

### ISSUE THREAD

**Issue by tokanggit** [palembang-digital/web-frontend#43]
Please add patal address at footer

Graha Edukasi, Jl. MP. Mangkunegara No.5, Bukit Sangkal, Kec. Kalidoni, Kota Palembang, Sumatera Selatan 30114

**Comment by salahudinalyb** [comment]
silahkan review kak 
https://www.figma.com/file/uaiuRP2SSywzXqvIrQ2HYh/patal_web?node-id=0%3A1

**Comment by tokanggit** [comment]
LGTM
