### ISSUE TITLE
Configure SEO

### ISSUE THREAD

**Issue by ariefrahmansyah** [palembang-digital/web-frontend#5]
To be able to track the performance of the website, we need to add SEO capability.

We can use `react-helmet` to do this.

Reference:
1. https://www.gatsbyjs.org/docs/add-page-metadata/
2. https://www.gatsbyjs.org/docs/add-seo-component/
3. https://medium.com/javascript-in-plain-english/how-to-connect-your-gatsby-js-landing-page-to-google-analytics-and-deploy-to-netlify-step-by-step-8352467583df

**Comment by ariefrahmansyah** [comment]
We can also refer to this article: https://medium.com/javascript-in-plain-english/how-to-connect-your-gatsby-js-landing-page-to-google-analytics-and-deploy-to-netlify-step-by-step-8352467583df

**Comment by tokanggit** [comment]
Google Analytics Tracking ID = UA-169186060-1

**Comment by ariefrahmansyah** [comment]
For now, I've added Google Analytics tracking to our website via Netlify's snippet injection [1]. 

This issue is still needed to track the progress for configuring better SEO [2], especially page metadata.

[1] https://docs.netlify.com/site-deploys/post-processing/snippet-injection/
[2] https://www.gatsbyjs.org/docs/seo

**Comment by tokanggit** [comment]
SEO content: 

- Homepage: Patal (Palembang Digital) adalah group berbagi informasi seputar IT Development & Digital di daerah Sumatera Selatan.

- Team Page: every members name

**Comment by ariefrahmansyah** [comment]
Can we change the description and SEO on the homepage? Instead of `Patal (Palembang Digital)`, it's better to write it `Palembang Digital (Patal)`. So we start with the real name followed by the abbreviation.

![image](https://user-images.githubusercontent.com/8122852/84855505-7b60af80-b08e-11ea-9644-fd873766572f.png)

@azhry @tokanggit

**Comment by tokanggit** [comment]
Sure, that is better
