### ISSUE TITLE
[INFRA] Setup patal staging

### ISSUE THREAD

**Issue by tokanggit** [palembang-digital/web-frontend#6]
Create subdomain staging-web.palembangdigital.org at Netlify, and setup CD/CI from staging branch at Github.

**Comment by ariefrahmansyah** [comment]
You can review to this documentation: https://docs.netlify.com/site-deploys/overview/#branches-and-deploys

**Comment by maximalyono** [comment]
ini sudah boleh di setup, atau menunggu developer siap bang?

**Comment by ariefrahmansyah** [comment]
> ini sudah boleh di setup, atau menunggu developer siap bang?

Sudah boleh disiapkan dari sekarang. Tapi kita akan minta developer untuk pake approach staging-master later ya.
